version: '3.8'
services:
  gitlab:
    image: "gitlab/gitlab-ce:17.7.0-ce.0"
    hostname: "gitlab_container"
    container_name: "gitlab_container"
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.anisa.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['time_zone'] = 'Tehran'

        # Renew every 7th day of the month at 12:30
        # letsencrypt['enable'] = true
        # letsencrypt['auto_renew_hour'] = "12"
        # letsencrypt['auto_renew_minute'] = "30"
        # letsencrypt['auto_renew_day_of_month'] = "*/7"

        # gitlab_rails['time_zone'] = 'America/Chicago'
        # gitlab_rails['gitlab_email_from'] = 'gitlab-no-reply@example.com'
        # gitlab_rails['gitlab_email_display_name'] = 'GitLab Administrator'
        # gitlab_rails['gitlab_email_reply_to'] = 'admin@hexample.com'
        # gitlab_rails['backup_keep_time'] = 14515200
        # gitlab_rails['smtp_enable'] = true
        # gitlab_rails['smtp_address'] = "smtp.example.com"
        # gitlab_rails['smtp_port'] = 587
        # gitlab_rails['smtp_user_name'] = "no-reply@example.com"
        # gitlab_rails['smtp_password'] = "changeMeToSomethingGood"
        # gitlab_rails['smtp_domain'] = "example.com"
        # gitlab_rails['smtp_authentication'] = "login"
        # gitlab_rails['smtp_enable_starttls_auto'] = true
        # unicorn['worker_timeout'] = 60
        # unicorn['worker_processes'] = 3
        # logging['logrotate_frequency'] = "weekly"
        # logging['logrotate_rotate'] = 52
        # logging['logrotate_compress'] = "compress"
        # logging['logrotate_method'] = "copytruncate"
        # logging['logrotate_delaycompress'] = "delaycompress"

        # Gitlab Nginx Config
        nginx['enable'] = true
        nginx['client_max_body_size'] = '250m'
        nginx['redirect_http_to_https'] = false
        nginx['gzip_enabled'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_protocol'] = false
        # nginx['listen_port'] = 443
        # nginx['redirect_http_to_https'] = true
        # nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server-cert.pem"
        # nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server-key.pem"
        # nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
        # nginx['logrotate_frequency'] = "weekly"
        # nginx['logrotate_rotate'] = 52
        # nginx['logrotate_compress'] = "compress"
        # nginx['logrotate_method'] = "copytruncate"
        # nginx['logrotate_delaycompress'] = "delaycompress"

        # Gitlab disable unused services
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        postgres_exporter['enable'] = false
        pgbouncer_exporter['enable'] = false
        gitlab_exporter['enable'] = false
        letsencrypt['enable'] = false
        prometheus['enable'] = false
        monitoring_role['enable'] = false
        alertmanager['enable'] = false
    ports:
      - "80:80"
      - "22:22"
      - "443:443"
    volumes:
      - /data/gitlab/config:/etc/gitlab
      - /data/gitlab/logs:/var/log/gitlab
      - /data/gitlab/data:/var/opt/gitlab
    networks:
      - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network

    # deploy:
    #   mode: replicated
    #   replicas: 1
    #   update_config:
    #     parallelism: 1
    #     #delay: 30s
    #     order: start-first
    #   #restart_policy:
    #     #condition: any
    #     #delay: 20s
    #     #window: 60s
    #   placement:
    #      constraints: [node.hostname == gitlab]


#password address:cat /data/gitlab/config/initial_root_password

